// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserByIdRequest
	UserByIdResponse
	UserByIdsRequest
	UserByIdsResponse
	UserByGouhaoRequest
	UserByGouhaoResponse
	User
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ------------------- single用户 by id -------------------
type UserByIdRequest struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *UserByIdRequest) Reset()                    { *m = UserByIdRequest{} }
func (m *UserByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*UserByIdRequest) ProtoMessage()               {}
func (*UserByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserByIdRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserByIdResponse struct {
	Code    int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	User    *User  `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *UserByIdResponse) Reset()                    { *m = UserByIdResponse{} }
func (m *UserByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*UserByIdResponse) ProtoMessage()               {}
func (*UserByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserByIdResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserByIdResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserByIdResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// ------------------- mulity用户 by ids -------------------
type UserByIdsRequest struct {
	Uids []int64 `protobuf:"varint,1,rep,packed,name=Uids" json:"Uids,omitempty"`
}

func (m *UserByIdsRequest) Reset()                    { *m = UserByIdsRequest{} }
func (m *UserByIdsRequest) String() string            { return proto.CompactTextString(m) }
func (*UserByIdsRequest) ProtoMessage()               {}
func (*UserByIdsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserByIdsRequest) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

type UserByIdsResponse struct {
	Code    int64   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Users   []*User `protobuf:"bytes,3,rep,name=Users" json:"Users,omitempty"`
}

func (m *UserByIdsResponse) Reset()                    { *m = UserByIdsResponse{} }
func (m *UserByIdsResponse) String() string            { return proto.CompactTextString(m) }
func (*UserByIdsResponse) ProtoMessage()               {}
func (*UserByIdsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserByIdsResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserByIdsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserByIdsResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// ------------------- single用户 by gouhao -------------------
type UserByGouhaoRequest struct {
	Gouhao int64 `protobuf:"varint,1,opt,name=Gouhao" json:"Gouhao,omitempty"`
}

func (m *UserByGouhaoRequest) Reset()                    { *m = UserByGouhaoRequest{} }
func (m *UserByGouhaoRequest) String() string            { return proto.CompactTextString(m) }
func (*UserByGouhaoRequest) ProtoMessage()               {}
func (*UserByGouhaoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserByGouhaoRequest) GetGouhao() int64 {
	if m != nil {
		return m.Gouhao
	}
	return 0
}

type UserByGouhaoResponse struct {
	Code    int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	User    *User  `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *UserByGouhaoResponse) Reset()                    { *m = UserByGouhaoResponse{} }
func (m *UserByGouhaoResponse) String() string            { return proto.CompactTextString(m) }
func (*UserByGouhaoResponse) ProtoMessage()               {}
func (*UserByGouhaoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserByGouhaoResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserByGouhaoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserByGouhaoResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id              int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Phone           string `protobuf:"bytes,3,opt,name=Phone" json:"Phone,omitempty"`
	Sex             int32  `protobuf:"varint,4,opt,name=Sex" json:"Sex,omitempty"`
	Status          int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	Avatar          string `protobuf:"bytes,6,opt,name=Avatar" json:"Avatar,omitempty"`
	Gouhao          int64  `protobuf:"varint,7,opt,name=Gouhao" json:"Gouhao,omitempty"`
	Avatars         string `protobuf:"bytes,8,opt,name=Avatars" json:"Avatars,omitempty"`
	Signature       string `protobuf:"bytes,9,opt,name=Signature" json:"Signature,omitempty"`
	GamePower       int64  `protobuf:"varint,10,opt,name=GamePower" json:"GamePower,omitempty"`
	Mark            int64  `protobuf:"varint,11,opt,name=Mark" json:"Mark,omitempty"`
	UserGroup       string `protobuf:"bytes,12,opt,name=UserGroup" json:"UserGroup,omitempty"`
	UserIcon        string `protobuf:"bytes,13,opt,name=UserIcon" json:"UserIcon,omitempty"`
	GreetWord       string `protobuf:"bytes,14,opt,name=GreetWord" json:"GreetWord,omitempty"`
	GreetWordFirst  int32  `protobuf:"varint,15,opt,name=GreetWordFirst" json:"GreetWordFirst,omitempty"`
	Invalid         int32  `protobuf:"varint,16,opt,name=Invalid" json:"Invalid,omitempty"`
	Level           int32  `protobuf:"varint,17,opt,name=Level" json:"Level,omitempty"`
	QuestionPhoto   string `protobuf:"bytes,18,opt,name=QuestionPhoto" json:"QuestionPhoto,omitempty"`
	BackGroundImage string `protobuf:"bytes,19,opt,name=BackGroundImage" json:"BackGroundImage,omitempty"`
	Lan             string `protobuf:"bytes,20,opt,name=Lan" json:"Lan,omitempty"`
	Notify          string `protobuf:"bytes,21,opt,name=Notify" json:"Notify,omitempty"`
	UniquePhone     string `protobuf:"bytes,22,opt,name=UniquePhone" json:"UniquePhone,omitempty"`
	CountryCode     string `protobuf:"bytes,23,opt,name=CountryCode" json:"CountryCode,omitempty"`
	Privacy         int32  `protobuf:"varint,24,opt,name=Privacy" json:"Privacy,omitempty"`
	LoadRecTags     int32  `protobuf:"varint,25,opt,name=LoadRecTags" json:"LoadRecTags,omitempty"`
	AccessToken     string `protobuf:"bytes,26,opt,name=AccessToken" json:"AccessToken,omitempty"`
	LoginPwd        string `protobuf:"bytes,27,opt,name=LoginPwd" json:"LoginPwd,omitempty"`
	Appfrom         string `protobuf:"bytes,28,opt,name=Appfrom" json:"Appfrom,omitempty"`
	Appver          string `protobuf:"bytes,29,opt,name=Appver" json:"Appver,omitempty"`
	UpdateAppver    string `protobuf:"bytes,30,opt,name=UpdateAppver" json:"UpdateAppver,omitempty"`
	AppfromOri      string `protobuf:"bytes,31,opt,name=AppfromOri" json:"AppfromOri,omitempty"`
	Appid           string `protobuf:"bytes,32,opt,name=Appid" json:"Appid,omitempty"`
	Birthday        int64  `protobuf:"varint,33,opt,name=Birthday" json:"Birthday,omitempty"`
	LastLogin       int64  `protobuf:"varint,34,opt,name=LastLogin" json:"LastLogin,omitempty"`
	Created         int64  `protobuf:"varint,35,opt,name=Created" json:"Created,omitempty"`
	Updated         int64  `protobuf:"varint,36,opt,name=Updated" json:"Updated,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetGouhao() int64 {
	if m != nil {
		return m.Gouhao
	}
	return 0
}

func (m *User) GetAvatars() string {
	if m != nil {
		return m.Avatars
	}
	return ""
}

func (m *User) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *User) GetGamePower() int64 {
	if m != nil {
		return m.GamePower
	}
	return 0
}

func (m *User) GetMark() int64 {
	if m != nil {
		return m.Mark
	}
	return 0
}

func (m *User) GetUserGroup() string {
	if m != nil {
		return m.UserGroup
	}
	return ""
}

func (m *User) GetUserIcon() string {
	if m != nil {
		return m.UserIcon
	}
	return ""
}

func (m *User) GetGreetWord() string {
	if m != nil {
		return m.GreetWord
	}
	return ""
}

func (m *User) GetGreetWordFirst() int32 {
	if m != nil {
		return m.GreetWordFirst
	}
	return 0
}

func (m *User) GetInvalid() int32 {
	if m != nil {
		return m.Invalid
	}
	return 0
}

func (m *User) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *User) GetQuestionPhoto() string {
	if m != nil {
		return m.QuestionPhoto
	}
	return ""
}

func (m *User) GetBackGroundImage() string {
	if m != nil {
		return m.BackGroundImage
	}
	return ""
}

func (m *User) GetLan() string {
	if m != nil {
		return m.Lan
	}
	return ""
}

func (m *User) GetNotify() string {
	if m != nil {
		return m.Notify
	}
	return ""
}

func (m *User) GetUniquePhone() string {
	if m != nil {
		return m.UniquePhone
	}
	return ""
}

func (m *User) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *User) GetPrivacy() int32 {
	if m != nil {
		return m.Privacy
	}
	return 0
}

func (m *User) GetLoadRecTags() int32 {
	if m != nil {
		return m.LoadRecTags
	}
	return 0
}

func (m *User) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *User) GetLoginPwd() string {
	if m != nil {
		return m.LoginPwd
	}
	return ""
}

func (m *User) GetAppfrom() string {
	if m != nil {
		return m.Appfrom
	}
	return ""
}

func (m *User) GetAppver() string {
	if m != nil {
		return m.Appver
	}
	return ""
}

func (m *User) GetUpdateAppver() string {
	if m != nil {
		return m.UpdateAppver
	}
	return ""
}

func (m *User) GetAppfromOri() string {
	if m != nil {
		return m.AppfromOri
	}
	return ""
}

func (m *User) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *User) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *User) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func init() {
	proto.RegisterType((*UserByIdRequest)(nil), "user.UserByIdRequest")
	proto.RegisterType((*UserByIdResponse)(nil), "user.UserByIdResponse")
	proto.RegisterType((*UserByIdsRequest)(nil), "user.UserByIdsRequest")
	proto.RegisterType((*UserByIdsResponse)(nil), "user.UserByIdsResponse")
	proto.RegisterType((*UserByGouhaoRequest)(nil), "user.UserByGouhaoRequest")
	proto.RegisterType((*UserByGouhaoResponse)(nil), "user.UserByGouhaoResponse")
	proto.RegisterType((*User)(nil), "user.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	UserById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*UserByIdResponse, error)
	UserByIds(ctx context.Context, in *UserByIdsRequest, opts ...grpc.CallOption) (*UserByIdsResponse, error)
	UserByGouhao(ctx context.Context, in *UserByGouhaoRequest, opts ...grpc.CallOption) (*UserByGouhaoResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*UserByIdResponse, error) {
	out := new(UserByIdResponse)
	err := grpc.Invoke(ctx, "/user.UserService/UserById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserByIds(ctx context.Context, in *UserByIdsRequest, opts ...grpc.CallOption) (*UserByIdsResponse, error) {
	out := new(UserByIdsResponse)
	err := grpc.Invoke(ctx, "/user.UserService/UserByIds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserByGouhao(ctx context.Context, in *UserByGouhaoRequest, opts ...grpc.CallOption) (*UserByGouhaoResponse, error) {
	out := new(UserByGouhaoResponse)
	err := grpc.Invoke(ctx, "/user.UserService/UserByGouhao", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	UserById(context.Context, *UserByIdRequest) (*UserByIdResponse, error)
	UserByIds(context.Context, *UserByIdsRequest) (*UserByIdsResponse, error)
	UserByGouhao(context.Context, *UserByGouhaoRequest) (*UserByGouhaoResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserById(ctx, req.(*UserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserByIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserByIds(ctx, req.(*UserByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserByGouhao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByGouhaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserByGouhao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserByGouhao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserByGouhao(ctx, req.(*UserByGouhaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserById",
			Handler:    _UserService_UserById_Handler,
		},
		{
			MethodName: "UserByIds",
			Handler:    _UserService_UserByIds_Handler,
		},
		{
			MethodName: "UserByGouhao",
			Handler:    _UserService_UserByGouhao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x3e, 0x21, 0x09, 0x90, 0x0d, 0xbf, 0xcb, 0xdf, 0x90, 0xc3, 0xe1, 0xb8, 0x06, 0xa1, 0xdc,
	0x94, 0x0b, 0x7a, 0x59, 0xa9, 0x12, 0x20, 0x35, 0x8a, 0x94, 0xd2, 0x34, 0x21, 0xea, 0x6d, 0xb7,
	0xde, 0x25, 0xb1, 0x20, 0x5e, 0xb3, 0x6b, 0x87, 0xe6, 0x39, 0xfb, 0x0e, 0x7d, 0x8e, 0x6a, 0x66,
	0xed, 0xc4, 0x49, 0x7b, 0x55, 0xa9, 0x77, 0xf3, 0x7d, 0x33, 0x3b, 0xff, 0x1e, 0x33, 0x96, 0x5a,
	0x65, 0x2e, 0x63, 0xa3, 0x13, 0xcd, 0x2b, 0x28, 0xfb, 0x67, 0x6c, 0x7b, 0x60, 0x95, 0xb9, 0x99,
	0xb6, 0x65, 0x4f, 0x3d, 0xa7, 0xca, 0x26, 0x7c, 0x87, 0x95, 0xd3, 0x50, 0x42, 0xc9, 0x2b, 0x35,
	0xcb, 0x3d, 0x14, 0xfd, 0x2f, 0x6c, 0x67, 0x6e, 0x64, 0x63, 0x1d, 0x59, 0xc5, 0x39, 0xab, 0x04,
	0x5a, 0xaa, 0xcc, 0x8c, 0x64, 0x0e, 0x6c, 0x6d, 0xac, 0xac, 0x15, 0x43, 0x05, 0x2b, 0x5e, 0xa9,
	0x59, 0xeb, 0xe5, 0x90, 0x9f, 0x32, 0x0a, 0x07, 0x65, 0xaf, 0xd4, 0xac, 0x5f, 0xb1, 0x4b, 0xca,
	0x03, 0x7d, 0xf6, 0x5c, 0x1a, 0x17, 0xf3, 0x08, 0x36, 0xcf, 0x83, 0xb3, 0xca, 0x20, 0x94, 0x16,
	0x4a, 0x5e, 0x19, 0x23, 0xa0, 0xec, 0x07, 0x6c, 0xb7, 0x60, 0xf7, 0x47, 0xa9, 0x78, 0xac, 0x8a,
	0x2e, 0x2c, 0x94, 0xbd, 0xf2, 0x52, 0x2e, 0x4e, 0xe1, 0xbf, 0x66, 0x7b, 0x2e, 0x48, 0x4b, 0xa7,
	0x23, 0xa1, 0xf3, 0x7c, 0x0e, 0xd9, 0xaa, 0x23, 0xb2, 0x40, 0x19, 0xf2, 0x25, 0xdb, 0x5f, 0x34,
	0xff, 0x2b, 0x1d, 0xfa, 0xb1, 0xc6, 0x2a, 0x08, 0xf9, 0x16, 0x5b, 0x69, 0xe7, 0xd3, 0x59, 0x69,
	0x4b, 0x0c, 0x73, 0x27, 0xc6, 0xb9, 0x3f, 0x92, 0xf9, 0x3e, 0xab, 0x76, 0x47, 0x3a, 0x52, 0xe4,
	0xad, 0xd6, 0x73, 0x00, 0x07, 0xdb, 0x57, 0xdf, 0xa0, 0xe2, 0x95, 0x9a, 0xd5, 0x1e, 0x8a, 0x58,
	0x52, 0x3f, 0x11, 0x49, 0x6a, 0xa1, 0x4a, 0x64, 0x86, 0x90, 0xbf, 0x9e, 0x88, 0x44, 0x18, 0x58,
	0x25, 0x07, 0x19, 0x2a, 0xb4, 0x60, 0xad, 0xd8, 0x02, 0x2c, 0xcb, 0x59, 0x58, 0x58, 0x77, 0x65,
	0x65, 0x90, 0x9f, 0xb0, 0x5a, 0x3f, 0x1c, 0x46, 0x22, 0x49, 0x8d, 0x82, 0x1a, 0xe9, 0xe6, 0x04,
	0x6a, 0x5b, 0x62, 0xac, 0xba, 0xfa, 0x45, 0x19, 0x60, 0xe4, 0x72, 0x4e, 0x60, 0x65, 0x1f, 0x84,
	0x79, 0x84, 0xba, 0x6b, 0x20, 0xca, 0xf8, 0x02, 0xbb, 0xd0, 0x32, 0x3a, 0x8d, 0x61, 0xc3, 0xf9,
	0x9b, 0x11, 0xbc, 0xc1, 0xd6, 0x11, 0xb4, 0x03, 0x1d, 0xc1, 0x26, 0x29, 0x67, 0x98, 0x62, 0x19,
	0xa5, 0x92, 0xcf, 0xda, 0x48, 0xd8, 0x72, 0x2f, 0x67, 0x04, 0xbf, 0x60, 0x5b, 0x33, 0xf0, 0x3e,
	0x34, 0x36, 0x81, 0x6d, 0xea, 0xc8, 0x12, 0x8b, 0x95, 0xb6, 0xa3, 0x89, 0x78, 0x0a, 0x25, 0xec,
	0x90, 0x41, 0x0e, 0xb1, 0xe7, 0x1d, 0x35, 0x51, 0x4f, 0xb0, 0x4b, 0xbc, 0x03, 0xfc, 0x9c, 0x6d,
	0x7e, 0xc2, 0xed, 0x09, 0x75, 0xd4, 0x1d, 0xe9, 0x44, 0x03, 0xa7, 0xc8, 0x8b, 0x24, 0x6f, 0xb2,
	0xed, 0x1b, 0x11, 0x3c, 0x62, 0x11, 0x91, 0x6c, 0x8f, 0x71, 0x3d, 0xf6, 0xc8, 0x6e, 0x99, 0xc6,
	0x19, 0x76, 0x44, 0x04, 0xfb, 0xa4, 0x45, 0x11, 0x67, 0x72, 0xa7, 0x93, 0xf0, 0x61, 0x0a, 0x07,
	0x6e, 0x56, 0x0e, 0x71, 0x8f, 0xd5, 0x07, 0x51, 0xf8, 0x9c, 0x2a, 0xb7, 0x09, 0x87, 0xa4, 0x2c,
	0x52, 0x68, 0x71, 0xab, 0xd3, 0x28, 0x31, 0xd3, 0x5b, 0xdc, 0xd3, 0x23, 0x67, 0x51, 0xa0, 0xb0,
	0xda, 0xae, 0x09, 0x27, 0x22, 0x98, 0x02, 0xb8, 0x6a, 0x33, 0x88, 0x6f, 0x3b, 0x5a, 0xc8, 0x9e,
	0x0a, 0xee, 0xc5, 0xd0, 0xc2, 0x31, 0x69, 0x8b, 0x14, 0x5a, 0x5c, 0x07, 0x81, 0xb2, 0xf6, 0x5e,
	0x3f, 0xaa, 0x08, 0x1a, 0xce, 0x7b, 0x81, 0xc2, 0x69, 0x75, 0xf4, 0x30, 0x8c, 0xba, 0x2f, 0x12,
	0xfe, 0x75, 0xd3, 0xca, 0x31, 0x6d, 0x54, 0x1c, 0x3f, 0x18, 0x3d, 0x86, 0x93, 0x6c, 0xa3, 0x1c,
	0xa4, 0xdd, 0x8c, 0xe3, 0x89, 0x32, 0xf0, 0x5f, 0xb6, 0x9b, 0x84, 0xb8, 0xcf, 0x36, 0x06, 0xb1,
	0x14, 0x89, 0xca, 0xb4, 0xa7, 0xa4, 0x5d, 0xe0, 0xf8, 0x29, 0x63, 0x99, 0x9b, 0x8f, 0x26, 0x84,
	0xff, 0xc9, 0xa2, 0xc0, 0xe0, 0x0c, 0xaf, 0xe3, 0x38, 0x94, 0xe0, 0xb9, 0xef, 0x86, 0x00, 0xe6,
	0x79, 0x13, 0x9a, 0x64, 0x24, 0xc5, 0x14, 0x5e, 0xd1, 0x2e, 0xce, 0x30, 0x6e, 0x55, 0x47, 0xd8,
	0x84, 0xf2, 0x06, 0xdf, 0x6d, 0xf0, 0x8c, 0xc0, 0x2a, 0x6e, 0x8d, 0x12, 0x89, 0x92, 0x70, 0x46,
	0xba, 0x1c, 0xa2, 0xc6, 0x65, 0x26, 0xe1, 0xdc, 0x69, 0x32, 0x78, 0xf5, 0xbd, 0xc4, 0xea, 0xb8,
	0xb4, 0x7d, 0x65, 0x26, 0x61, 0xa0, 0xf8, 0x5b, 0xb7, 0xd3, 0x78, 0xf2, 0xf8, 0xc1, 0xfc, 0x2c,
	0x14, 0x2e, 0x76, 0xe3, 0x70, 0x99, 0x76, 0x17, 0xc8, 0xff, 0x87, 0xbf, 0x73, 0x9f, 0x0b, 0xdd,
	0x4b, 0xbe, 0x64, 0x96, 0x1f, 0xda, 0xc6, 0xd1, 0x2f, 0xfc, 0xec, 0x7d, 0x8b, 0x6d, 0x14, 0x6f,
	0x1b, 0x3f, 0x2e, 0x9a, 0x2e, 0x9c, 0xc7, 0x46, 0xe3, 0x77, 0xaa, 0xdc, 0xd1, 0xd7, 0x55, 0xfa,
	0xe9, 0xbc, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x60, 0xc3, 0xd5, 0xc9, 0x82, 0x06, 0x00, 0x00,
}
